= F1044 - Large 7-Seg Display Firmware
rev 1-dev

== Purpose
The purpose of this document is to describe the F1044 firmware.

== Development Information

=== Toolchain
The following tools and libraries are used to build this library:

[%autowidth]
|===
|Type|Name|Revision

|IDE
|Arduino IDE
|2.3.2

|Arduino Board
|esp32 by Espressif
|3.2.0
|===

=== Target
This firmware is only designed to be ran on an ESP32-Pico-D4 on an E1041 PCBA.

== Functional Description
The F1044 firmware controls up to 4 7-segment displays. The displays are intended to be 4" displays.

NOTE: While the firmware can handle up to 8 displays as per hardware, it has not been tested yet!

=== Modes
This firmware has the following run-time modes:

* *off* : The displays are disabled, nothing is displayed
* *numb* : Shows a static number on the display. Useful for host updated numeric display
* *time*: Shows the current time based off the timezone set.

The default timezone is EDT (mine!), but can be changed with the `set timeZone` command

=== Time Format

When displaying time, this firmware can present that in the following modes:

* *24hr*: Displays the time as HH:MM in 24-hour format
* *12hr*: Displays the time as HH:MM in 12-hour format. No AM/PM indicator can be shown in this mode
* *metric*: Displays the time as HH:MM in metric format. See https://metric-time.com/ for more information on this format

=== NVM
This firmware stores some parameters in non-volatile memory (nvm). The esp32-arduino's `EEPROM` is used, handling data storage and integrity.
The following table describes what is stored.

[%autowidth]
|===
|Offset|Length|Type|Description

|0
|1
|byte
|NVM magic to check if something is written. Should be 0x5A

|1
|32
|str
|WIFI SSID to connect to

|33
|32
|str
|WIFI password to connect to

|===

=== Communication
This firmware is communicated with over the following interfaces:

* Serial over USB, 115200 baud, 8N1
* Ethernet, telnet, port 23

All command frames sent to/from the device are in ASCII text mode, with either carriage-return (\r) or line-feed (\n) ending per frame.

If a command doesn't sent back a return value, an acknowlegment (ACK) may be sent back as the string "ok".
Any non-acknowlegments (NACK) may be sent as "error: X", where X is a human description of the error.

==== Ethernet, Telnet
This firmware handles being connected over Telnet directly, allowing to connect to this firmware over the built-in `telnet` command on many UNIX systems.

The following telnet commands are handled:

* DO
* WILL
* Interrupt Process, including waiting for timing-mark to responds with a new line and flush the internal receive buffer

This firmware also implements a "exit" command to close a Telnet connection.

[page-layout=landscape]
<<<


== Commands
The commands are structured as verb-noun system; the verb dictates the action, and noun is what to apply the verb to. For example "get mode" requests to "get" the "mode".
The verb and noun are space delimited. Any argument(s) to the command are also space delimited.

The following table list all the commands:

// [%autowidth]
[cols="1,2,5,5,6"]
|===
|Verb|Noun|Arguments|Return|Desc

|ping
|
|
|pong!
|ping-pong!

.8+|set
|mode
|[str], mode
|ACK
|Set the new mode, which is the same string as described in <<Modes>>

|n
|The number to display to in "numb" mode
|ACK, only if in "numb" mode
|

|timeFormat
a|[str], The new time format, either:

- '24hr'
- '12hr'
- 'metric'
|
|Sets the displayed time format, which is the same string as described in <<Time Format>>

|wifiSSID
|SSID
|
|Sets the WiFi SSID

|wifiPass
|password
|
|Sets the WiFi password

|wifiOff
|
|
|Turns wifi on if disabled and not running

|wifiOn
|password
|
|Turns wifi off if enabled and running

|timeZone
|The timezone as a TZ string. Use the command "get allTimeZones" to get valid timezones
|
|

.7+|get
|version
|
|The firmware version
|

|mode
|
|The current mode
|

|n
|
|The current displayed number
|

|timeFormat
|
|The time format
|See <<Time Format>>

|ip
|
|The current IP address of either Ethernet or Wifi, or "none" if not connected to the internet
|

|wifiInfo
|
|The current WiFi SSID and Password set
|

|allTimeZones
|
|All valid time zones
|

.4+|update
|begin
|The firmware size in bytes
|
|Starts a firmware update

|cont
|The number of bytes to send, then the raw bytes after reception of the first ACK
|ACK, followed by another ACK after raw bytes received
|When this command is received with the number of bytes to send, an ACK is sent. The firmware then expects
 that many bytes (not ASCII) to be received, in which another ACK will be sent after all expected bytes are received

|end
|
|
|Finishes the firmware update process

|cancel
|
|
|Cancels any on-going firmware update process

|saveNvm
|
|
|
|Saves the current NVM configuration

|exit
|
|
|
|In Telnet mode, this command sends the required Telnet commands to disconnect.

|reboot
|
|
|
|Reboots the microcontroller
|===
